var annotated_dup =
[
    [ "cogui_app", "structcogui__app.html", "structcogui__app" ],
    [ "cogui_box", "structcogui__box.html", "structcogui__box" ],
    [ "cogui_container", "structcogui__container.html", "structcogui__container" ],
    [ "cogui_couser", "structcogui__couser.html", "structcogui__couser" ],
    [ "cogui_dc", "structcogui__dc.html", "structcogui__dc" ],
    [ "cogui_dc_buffer", "structcogui__dc__buffer.html", "structcogui__dc__buffer" ],
    [ "cogui_dc_engine", "structcogui__dc__engine.html", "structcogui__dc__engine" ],
    [ "cogui_dc_hw", "structcogui__dc__hw.html", "structcogui__dc__hw" ],
    [ "cogui_event", "structcogui__event.html", "structcogui__event" ],
    [ "cogui_event_app", "structcogui__event__app.html", "structcogui__event__app" ],
    [ "cogui_event_kbd", "structcogui__event__kbd.html", "structcogui__event__kbd" ],
    [ "cogui_event_mouse", "structcogui__event__mouse.html", "structcogui__event__mouse" ],
    [ "cogui_event_win", "structcogui__event__win.html", null ],
    [ "cogui_event_win_create", "structcogui__event__win__create.html", "structcogui__event__win__create" ],
    [ "cogui_event_win_move", "structcogui__event__win__move.html", "structcogui__event__win__move" ],
    [ "cogui_event_win_resize", "structcogui__event__win__resize.html", "structcogui__event__win__resize" ],
    [ "cogui_event_win_set_title", "structcogui__event__win__set__title.html", "structcogui__event__win__set__title" ],
    [ "cogui_gc", "structcogui__gc.html", "structcogui__gc" ],
    [ "cogui_graphic_driver", "structcogui__graphic__driver.html", "structcogui__graphic__driver" ],
    [ "cogui_list_node", "structcogui__list__node.html", "structcogui__list__node" ],
    [ "cogui_point", "structcogui__point.html", "structcogui__point" ],
    [ "cogui_rect", "structcogui__rect.html", "structcogui__rect" ],
    [ "cogui_region", "structcogui__region.html", "structcogui__region" ],
    [ "cogui_region_data", "structcogui__region__data.html", "structcogui__region__data" ],
    [ "cogui_screen", "structcogui__screen.html", "structcogui__screen" ],
    [ "cogui_slist_node", "structcogui__slist__node.html", "structcogui__slist__node" ],
    [ "cogui_topwin", "structcogui__topwin.html", "structcogui__topwin" ],
    [ "cogui_widget", "structcogui__widget.html", "structcogui__widget" ],
    [ "cogui_window", "structcogui__window.html", "structcogui__window" ],
    [ "graphic_driver_ops", "structgraphic__driver__ops.html", "structgraphic__driver__ops" ],
    [ "graphic_ext_ops", "structgraphic__ext__ops.html", "structgraphic__ext__ops" ]
];